name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2.2'
    - uses: actions/checkout@v3
    - name: Copy src/Infrastructure/Laravel/.env
      run: php -r "file_exists('src/Infrastructure/Laravel/.env') || copy('src/Infrastructure/Laravel/.env.example', 'src/Infrastructure/Laravel/.env');"
    - name: Install Dependencies
      run: cd src/Infrastructure/Laravel/ && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: cd src/Infrastructure/Laravel/ && php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 src/Infrastructure/Laravel/storage src/Infrastructure/Laravel/bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p src/Infrastructure/Laravel/database
        touch src/Infrastructure/Laravel/database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: cd src/Infrastructure/Laravel/ && vendor/bin/phpunit
